server:
  port: 8000
  error:
    include-message: always
  servlet:
    context-path: /white-rabbit

spring:
  application:
    name: White Rabbit
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://jnjperseusu1:5432/shared
    username: white_rabbit
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

files-manager-url: http://jnjperseusu1/files-manager

fake-data-db:
  db-type: PostgreSQL
  server: jnjperseusu1
  port: 5433
  database: perseus
  user: perseus
  password: password