server:
  port: 8000
  error:
    include-message: always
  servlet:
    context-path: /white-rabbit

spring:
  application:
    name: White Rabbit
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://shareddb:5432/shared
    username: white_rabbit
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false

files-manager-url: http://files-manager:10500/files-manager

fake-data-db:
  db-type: PostgreSQL
  server: jnjcicdu1
  port: 5431
  database: cdm_souffleur
  user: postgres
  password: 5eC_DkMr^3