CREATE INDEX INDEX_VISIT_OCCURRENCE_PLACE_OF_SERVICE_CONCEPT_ID ON VISIT_OCCURRENCE (PLACE_OF_SERVICE_CONCEPT_ID ASC);
CREATE INDEX INDEX_VISIT_PLACE_OF_SERVICE_SOURCE_VALUE ON VISIT_OCCURRENCE (PLACE_OF_SERVICE_SOURCE_VALUE ASC);
CREATE INDEX INDEX_VISIT_VISIT_START_DATE ON VISIT_OCCURRENCE (VISIT_START_DATE ASC);
CREATE INDEX INDEX_VISIT_VISIT_END_DATE ON VISIT_OCCURRENCE (VISIT_END_DATE ASC);
CREATE INDEX INDEX_VISIT_OCCURRENCE_PERSON_ID ON VISIT_OCCURRENCE (PERSON_ID ASC);

CREATE INDEX INDEX_COHORT_COHORT_CONCEPT_ID ON COHORT (COHORT_CONCEPT_ID ASC);
CREATE INDEX INDEX_COHORT_COHORT_START_DATE ON COHORT (COHORT_START_DATE ASC);
CREATE INDEX INDEX_COHORT_COHORT_END_DATE ON COHORT (COHORT_END_DATE ASC);
CREATE INDEX INDEX_COHORT_SUBJECT_ID ON COHORT (SUBJECT_ID ASC);

CREATE INDEX INDEX_PROCEDURE_OCCURRENCE_PROCEDURE_OCCURRENCE_ID ON PROCEDURE_OCCURRENCE (PROCEDURE_OCCURRENCE_ID ASC);
CREATE INDEX INDEX_PROCEDURE_OCCURRENCE_PROCEDURE_TYPE_CONCEPT_ID ON PROCEDURE_OCCURRENCE (PROCEDURE_TYPE_CONCEPT_ID ASC);
CREATE INDEX INDEX_PROCEDURE_OCCURRENCE_PROCEDURE_SOURCE_VALUE ON PROCEDURE_OCCURRENCE (PROCEDURE_SOURCE_VALUE ASC);
CREATE INDEX INDEX_PROCEDURE_OCCURRENCE_PROCEDURE_DATE ON PROCEDURE_OCCURRENCE (PROCEDURE_DATE ASC);
CREATE INDEX INDEX_PROCEDURE_OCCURRENCE_PERSON_ID ON PROCEDURE_OCCURRENCE (PERSON_ID ASC);

CREATE INDEX INDEX_PROCEDURE_COST_PROCEDURE_OCCURRENCE_ID ON PROCEDURE_COST (PROCEDURE_OCCURRENCE_ID ASC);
CREATE INDEX INDEX_PROCEDURE_COST_DISEASE_CLASS_CONCEPT_ID ON PROCEDURE_COST (DISEASE_CLASS_CONCEPT_ID ASC);
CREATE INDEX INDEX_PROCEDURE_COST_DISEASE_CLASS_SOURCE_VALUE ON PROCEDURE_COST (DISEASE_CLASS_SOURCE_VALUE ASC);

CREATE INDEX INDEX_PROVIDER_PROVIDER_ID ON PROVIDER (PROVIDER_ID ASC);
CREATE INDEX INDEX_PROVIDER_SPECIALTY_CONCEPT_ID ON PROVIDER (SPECIALTY_CONCEPT_ID ASC);
CREATE INDEX INDEX_PROVIDER_SPECIALTY_SOURCE_VALUE ON PROVIDER (SPECIALTY_SOURCE_VALUE ASC);

CREATE INDEX INDEX_PERSON_PERSON_ID ON PERSON (PERSON_ID ASC);

CREATE INDEX INDEX_OBSERVATION_OBSERVATION_PERIOD_START_DATE ON OBSERVATION_PERIOD (OBSERVATION_PERIOD_START_DATE ASC);
CREATE INDEX INDEX_OBSERVATION_OBSERVATION_PERIOD_END_DATE ON OBSERVATION_PERIOD (OBSERVATION_PERIOD_END_DATE ASC);
CREATE INDEX INDEX_OBSERVATION_PERIOD_PERSON_ID ON OBSERVATION_PERIOD (PERSON_ID ASC);

CREATE INDEX INDEX_OBSERVATION_OBSERVATION_CONCEPT_ID ON OBSERVATION (OBSERVATION_CONCEPT_ID ASC);
CREATE INDEX INDEX_OBSERVATION_OBSERVATION_DATE ON OBSERVATION (OBSERVATION_DATE ASC);
CREATE INDEX INDEX_OBSERVATION_PERSON_ID ON OBSERVATION (PERSON_ID ASC);

CREATE INDEX INDEX_DRUG_ERA_DRUG_CONCEPT_ID ON DRUG_ERA (DRUG_CONCEPT_ID ASC);
CREATE INDEX INDEX_DRUG_ERA_DRUG_ERA_START_DATE ON DRUG_ERA (DRUG_ERA_START_DATE ASC);
CREATE INDEX INDEX_DRUG_ERA_DRUG_ERA_END_DATE ON DRUG_ERA (DRUG_ERA_END_DATE ASC);
CREATE INDEX INDEX_DRUG_ERA_PERSON_ID ON DRUG_ERA (PERSON_ID ASC);

CREATE INDEX INDEX_DRUG_EXPOSURE_DRUG_CONCEPT_ID ON DRUG_EXPOSURE (DRUG_CONCEPT_ID ASC);
CREATE INDEX INDEX_DRUG_EXPOSURE_DRUG_SOURCE_VALUE ON DRUG_EXPOSURE (DRUG_SOURCE_VALUE ASC);
CREATE INDEX INDEX_DRUG_EXPOSURE_DRUG_EXPOSURE_START_DATE ON DRUG_EXPOSURE (DRUG_EXPOSURE_START_DATE ASC);
CREATE INDEX INDEX_DRUG_EXPOSURE_DRUG_EXPOSURE_END_DATE ON DRUG_EXPOSURE (DRUG_EXPOSURE_END_DATE ASC);
CREATE INDEX INDEX_DRUG_EXPOSURE_PERSON_ID ON DRUG_EXPOSURE (PERSON_ID ASC);

CREATE INDEX INDEX_DEATH_DEATH_DATE ON DEATH (DEATH_DATE ASC);
CREATE INDEX INDEX_DEATH_PERSON_ID ON DEATH (PERSON_ID ASC);

CREATE INDEX INDEX_CONDITION_ERA_CONDITION_CONCEPT_ID ON CONDITION_ERA (CONDITION_CONCEPT_ID ASC);
CREATE INDEX INDEX_CONDITION_ERA_CONDITION_ERA_START_DATE ON CONDITION_ERA (CONDITION_ERA_START_DATE ASC);
CREATE INDEX INDEX_CONDITION_ERA_CONDITION_ERA_END_DATE ON CONDITION_ERA (CONDITION_ERA_END_DATE ASC);
CREATE INDEX INDEX_CONDITION_ERA_PERSON_ID ON CONDITION_ERA (PERSON_ID ASC);

CREATE INDEX INDEX_CONDITION_OCCURRENCE_CONDITION_CONCEPT_ID ON CONDITION_OCCURRENCE (CONDITION_CONCEPT_ID ASC);
CREATE INDEX INDEX_CONDITION_OCCURRENCE_CONDITION_SOURCE_VALUE ON CONDITION_OCCURRENCE (CONDITION_SOURCE_VALUE ASC);
CREATE INDEX INDEX_CONDITION_OCCURRENCE_CONDITION_START_DATE ON CONDITION_OCCURRENCE (CONDITION_START_DATE ASC);
CREATE INDEX INDEX_CONDITION_OCCURRENCE_CONDITION_END_DATE ON CONDITION_OCCURRENCE (CONDITION_END_DATE ASC);
CREATE INDEX INDEX_CONDITION_OCCURRENCE_PERSON_ID ON CONDITION_OCCURRENCE (PERSON_ID ASC);


