CREATE TABLE IF NOT EXISTS `CARE_SITE` (
	`CARE_SITE_ID` INT NOT NULL,
	`LOCATION_ID` INT NULL,
	`ORGANIZATION_ID` INT NULL,
	`PLACE_OF_SERVICE_CONCEPT_ID` INT NULL,
	`CARE_SITE_SOURCE_VALUE` VARCHAR(50) NULL,
	`PLACE_OF_SERVICE_SOURCE_VALUE` VARCHAR(50) NULL
);

CREATE TABLE IF NOT EXISTS `COHORT` (
	`COHORT_ID` INT AUTO_INCREMENT PRIMARY KEY,
	`COHORT_CONCEPT_ID` INT NOT NULL,
	`COHORT_START_DATE` DATE NOT NULL,
	`COHORT_END_DATE` DATE NULL,
	`SUBJECT_ID` BIGINT NOT NULL,
	`STOP_REASON` VARCHAR(20) NULL
);

CREATE TABLE IF NOT EXISTS `CONDITION_ERA` (
	`CONDITION_ERA_ID` BIGINT NOT NULL,
	`PERSON_ID` BIGINT NOT NULL,
	`CONDITION_CONCEPT_ID` INT NOT NULL,
	`CONDITION_ERA_START_DATE` DATE NOT NULL,
	`CONDITION_ERA_END_DATE` DATE NOT NULL,
	`CONDITION_TYPE_CONCEPT_ID` INT NOT NULL,
	`CONDITION_OCCURRENCE_COUNT` INT NULL
);

CREATE TABLE IF NOT EXISTS `CONDITION_OCCURRENCE` (
	`CONDITION_OCCURRENCE_ID` BIGINT NOT NULL,
	`PERSON_ID` BIGINT NOT NULL,
	`CONDITION_CONCEPT_ID` INT NOT NULL,
	`CONDITION_START_DATE` DATE NOT NULL,
	`CONDITION_END_DATE` DATE NULL,
	`CONDITION_TYPE_CONCEPT_ID` INT NOT NULL,
	`STOP_REASON` VARCHAR(20) NULL,
	`ASSOCIATED_PROVIDER_ID` INT NULL,
	`VISIT_OCCURRENCE_ID` BIGINT NULL,
	`CONDITION_SOURCE_VALUE` VARCHAR(50) NULL
);

CREATE TABLE IF NOT EXISTS `DEATH` (
	`PERSON_ID` BIGINT NOT NULL,
	`DEATH_DATE` DATE NOT NULL,
	`DEATH_TYPE_CONCEPT_ID` INT NOT NULL,
	`CAUSE_OF_DEATH_CONCEPT_ID` INT NULL,
	`CAUSE_OF_DEATH_SOURCE_VALUE` VARCHAR(50) NULL
);

CREATE TABLE IF NOT EXISTS `DRUG_COST` (
	`DRUG_COST_ID` BIGINT NOT NULL,
	`DRUG_EXPOSURE_ID` BIGINT NOT NULL,
	`PAID_COPAY` NUMERIC NULL,
	`PAID_COINSURANCE` NUMERIC NULL,
	`PAID_TOWARD_DEDUCTIBLE` NUMERIC NULL,
	`PAID_BY_PAYER` NUMERIC NULL,
	`PAID_BY_COORDINATION_BENEFITS` NUMERIC NULL,
	`TOTAL_OUT_OF_POCKET` NUMERIC NULL,
	`TOTAL_PAID` NUMERIC NULL,
	`INGREDIENT_COST` NUMERIC NULL,
	`DISPENSING_FEE` NUMERIC NULL,
	`AVERAGE_WHOLESALE_PRICE` NUMERIC NULL,
	`PAYER_PLAN_PERIOD_ID` INT NULL
);

CREATE TABLE IF NOT EXISTS `DRUG_ERA` (
	`DRUG_ERA_ID` BIGINT NOT NULL,
	`PERSON_ID` BIGINT NOT NULL,
	`DRUG_ERA_START_DATE` DATE NOT NULL,
	`DRUG_ERA_END_DATE` DATE NOT NULL,
	`DRUG_TYPE_CONCEPT_ID` INT NOT NULL,
	`DRUG_CONCEPT_ID` INT NULL,
	`DRUG_EXPOSURE_COUNT` INT NOT NULL
);

CREATE TABLE IF NOT EXISTS `DRUG_EXPOSURE` (
	`DRUG_EXPOSURE_ID` BIGINT NOT NULL,
	`PERSON_ID` BIGINT NOT NULL,
	`DRUG_CONCEPT_ID` INT NOT NULL,
	`DRUG_EXPOSURE_START_DATE` DATE NOT NULL,
	`DRUG_EXPOSURE_END_DATE` DATE NULL,
	`DRUG_TYPE_CONCEPT_ID` INT NOT NULL,
	`STOP_REASON` VARCHAR(20) NULL,
	`REFILLS` INT NULL,
	`QUANTITY` INT NULL,
	`DAYS_SUPPLY` INT NULL,
	`SIG` VARCHAR(500) NULL,
	`PRESCRIBING_PROVIDER_ID` INT NULL,
	`VISIT_OCCURRENCE_ID` BIGINT NULL,
	`RELEVANT_CONDITION_CONCEPT_ID` INT NULL,
	`DRUG_SOURCE_VALUE` VARCHAR(50) NULL
);

CREATE TABLE IF NOT EXISTS `LOCATION` (
	`LOCATION_ID` INT NOT NULL,
	`ADDRESS_1` VARCHAR(50) NULL,
	`ADDRESS_2` VARCHAR(50) NULL,
	`CITY` VARCHAR(50) NULL,
	`STATE` CHAR(2) NULL,
	`ZIP` VARCHAR(9) NULL,
	`COUNTY` VARCHAR(20) NULL,
	`LOCATION_SOURCE_VALUE` VARCHAR(50) NULL
);

CREATE TABLE IF NOT EXISTS `OBSERVATION` (
	`OBSERVATION_ID` BIGINT NOT NULL,
	`PERSON_ID` BIGINT NOT NULL,
	`OBSERVATION_CONCEPT_ID` BIGINT NOT NULL,
	`OBSERVATION_TYPE_CONCEPT_ID` INT NOT NULL,
	`OBSERVATION_DATE` DATE NOT NULL,
	`OBSERVATION_TIME` TIME NULL,
	`VALUE_AS_NUMBER` NUMERIC NULL,
	`VALUE_AS_STRING` VARCHAR(256) NULL,
	`VALUE_AS_CONCEPT_ID` INT NULL,
	`UNIT_CONCEPT_ID` BIGINT NULL,
	`RANGE_LOW` FLOAT NULL,
	`RANGE_HIGH` FLOAT NULL,
	`ASSOCIATED_PROVIDER_ID` INT NULL,
	`VISIT_OCCURRENCE_ID` BIGINT NULL,
	`OBSERVATION_SOURCE_VALUE` VARCHAR(256) NULL,
	`UNIT_SOURCE_VALUE` VARCHAR(256) NULL,
	`RELEVANT_CONDITION_CONCEPT_ID` INT NULL
);

CREATE TABLE IF NOT EXISTS `OBSERVATION_PERIOD` (
	`OBSERVATION_PERIOD_ID` BIGINT NOT NULL,
	`PERSON_ID` BIGINT NOT NULL,
	`OBSERVATION_PERIOD_START_DATE` DATE NOT NULL,
	`OBSERVATION_PERIOD_END_DATE` DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS `ORGANIZATION` (
	`ORGANIZATION_ID` INT NOT NULL,
	`PLACE_OF_SERVICE_CONCEPT_ID` INT NULL,
	`LOCATION_ID` INT NULL,
	`ORGANIZATION_SOURCE_VALUE` VARCHAR(50) NULL,
	`PLACE_OF_SERVICE_SOURCE_VALUE` VARCHAR(50) NULL
);

CREATE TABLE IF NOT EXISTS `PAYER_PLAN_PERIOD` (
	`PAYER_PLAN_PERIOD_ID` BIGINT NOT NULL,
	`PERSON_ID` BIGINT NOT NULL,
	`PAYER_PLAN_PERIOD_START_DATE` DATE NOT NULL,
	`PAYER_PLAN_PERIOD_END_DATE` DATE NOT NULL,
	`PAYER_SOURCE_VALUE` VARCHAR(50) NULL,
	`PLAN_SOURCE_VALUE` VARCHAR(50) NULL,
	`FAMILY_SOURCE_VALUE` VARCHAR(50) NULL
);

CREATE TABLE IF NOT EXISTS `PERSON` (
	`PERSON_ID` BIGINT NOT NULL,
	`GENDER_CONCEPT_ID` INT NOT NULL,
	`YEAR_OF_BIRTH` INT NOT NULL,
	`MONTH_OF_BIRTH` INT NULL,
	`DAY_OF_BIRTH` INT NULL,
	`RACE_CONCEPT_ID` INT NULL,
	`ETHNICITY_CONCEPT_ID` INT NULL,
	`LOCATION_ID` INT NULL,
	`PROVIDER_ID` INT NULL,
	`CARE_SITE_ID` INT NULL,
	`PERSON_SOURCE_VALUE` VARCHAR(50) NULL,
	`GENDER_SOURCE_VALUE` VARCHAR(50) NULL,
	`RACE_SOURCE_VALUE` VARCHAR(50) NULL,
	`ETHNICITY_SOURCE_VALUE` VARCHAR(50) NULL
);

CREATE TABLE IF NOT EXISTS `PROCEDURE_COST` (
	`PROCEDURE_COST_ID` BIGINT NOT NULL,
	`PROCEDURE_OCCURRENCE_ID` BIGINT NOT NULL,
	`PAID_COPAY` NUMERIC NULL,
	`PAID_COINSURANCE` NUMERIC NULL,
	`PAID_TOWARD_DEDUCTIBLE` NUMERIC NULL,
	`PAID_BY_PAYER` NUMERIC NULL,
	`PAID_BY_COORDINATION_BENEFITS` NUMERIC NULL,
	`TOTAL_OUT_OF_POCKET` NUMERIC NULL,
	`TOTAL_PAID` NUMERIC NULL,
	`DISEASE_CLASS_CONCEPT_ID` INT NULL,
	`REVENUE_CODE_CONCEPT_ID` INT NULL,
	`PAYER_PLAN_PERIOD_ID` BIGINT NULL,
	`DISEASE_CLASS_SOURCE_VALUE` VARCHAR(50) NULL,
	`REVENUE_CODE_SOURCE_VALUE` VARCHAR(50) NULL
);

CREATE TABLE IF NOT EXISTS `PROCEDURE_OCCURRENCE` (
	`PROCEDURE_OCCURRENCE_ID` BIGINT NOT NULL,
	`PERSON_ID` BIGINT NOT NULL,
	`PROCEDURE_TYPE_CONCEPT_ID` INT NOT NULL,
	`PROCEDURE_DATE` DATE NOT NULL,
	`PROCEDURE_CONCEPT_ID` BIGINT NOT NULL,
	`ASSOCIATED_PROVIDER_ID` INT NULL,
	`PROCEDURE_SOURCE_VALUE` VARCHAR(50) NULL,
	`VISIT_OCCURRENCE_ID` BIGINT NULL,
	`RELEVANT_CONDITION_CONCEPT_ID` INT NULL
);

CREATE TABLE IF NOT EXISTS `PROVIDER` (
	`PROVIDER_ID` BIGINT NOT NULL,
	`NPI` VARCHAR(20) NULL,
	`DEA` VARCHAR(20) NULL,
	`SPECIALTY_CONCEPT_ID` INT NULL,
	`CARE_SITE_ID` INT NULL,
	`PROVIDER_SOURCE_VALUE` VARCHAR(50) NULL,
	`SPECIALTY_SOURCE_VALUE` VARCHAR(50) NULL
);

CREATE TABLE IF NOT EXISTS `VISIT_OCCURRENCE` (
	`VISIT_OCCURRENCE_ID` BIGINT NOT NULL,
	`PERSON_ID` BIGINT NOT NULL,
	`PLACE_OF_SERVICE_CONCEPT_ID` INT NOT NULL,
	`VISIT_START_DATE` DATE NOT NULL,
	`VISIT_END_DATE` DATE NOT NULL,
	`PLACE_OF_SERVICE_SOURCE_VALUE` VARCHAR(50) NULL,
	`CARE_SITE_ID` INT NULL
);
